config/routes.rb
Rails.application.routes.draw do

  get   '/start', :to => 'sessions#checklogin', :as => :start

  get '/login',:to => 'sessions#login',:as => :login

  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#failure'
  get 'logout' => 'sessions#destroy'

  root :to => redirect('/start')

  resources :users do
    resources :events
  end

  get 'users/:id/view' => 'users#view',:as=> :showprofile
  get 'users/:id/displayUsers' => 'users#displayUsers',:as=> :displayUsers
  get 'users/:id/:name/addFriend' => 'users#addFriend',:as=> :addFriend
  get 'users/:id/setMeeting/:friend_id' => 'users#setMeeting',:as=> :set_up_a_meeting

  get 'users/:id/showFriend/:friend_id' => 'users#showFriend',:as=> :showFriend

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	attr_accessible :title, :ownerid, :starttime, :endtime, :duration, :location, :status, :description, :user_id

	#attr_protected :user_id

	

end

app/models/friend.rb
class Friend < ActiveRecord::Base
	belongs_to :user
	attr_accessible :uid, :provider, :name,:first_name,:last_name,:about,:gender,:work,:email,:education, :user_id
	def self.getHash (_name)
		friend_to_add = User.find_by_name(_name);
		hash = {:uid => friend_to_add.uid, :provider=>friend_to_add.provider, 
			:name=>friend_to_add.name,:first_name=>friend_to_add.first_name,
			:last_name=>friend_to_add.last_name,:about=>friend_to_add.about,
			:gender=>friend_to_add.gender,:work=>friend_to_add.work,
			:email=>friend_to_add.email,:education=>friend_to_add.education}
			# :user_id => params[:id]}
			return hash
	end
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :events
	has_many :friends
	attr_accessible :uid, :provider, :name,:first_name,:last_name,:about,:gender,:work,:email,:education
	def self.create_with_omniauth(auth)
		User.create!(
			:provider => auth["provider"],
			:uid => auth["uid"],
			:name => auth["info"]["name"],
			:first_name => auth["info"]["first_name"],
			:last_name => auth["info"]["last_name"],
			:about => auth["info"]["about"],
			:gender => auth["extra"]["raw_info"]["gender"],
			:work => auth["info"]["work"],
			:email => auth["info"]["email"],
			:education => auth["info"]["education"])

	end
	def self.notYetFriends currUser
		usersToNotDisplay = []
		usersToNotDisplay << currUser

		currUserFriends = currUser.friends

		if currUserFriends != nil
			currUserFriends.each { |friend| 
				usersToNotDisplay << User.find_by_name(friend.name)
			}
		end

		allusers = User.all
		allusers -= usersToNotDisplay
		return allusers
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

def new
	@event = Event.new
	@event = Event.find_by_id(params[:id]);
	

end


def create
	#params[:event][:duration] = params[:event][:endtime] - params[:event][:startime]
	params[:event][:user_id] = session[:user_id]
	@temp = params[:event][:title]
	# logger.debug("VALUE OF TITLW: ")
	# logger.debug(params[:event][:title])

	if params[:event][:title] == ""
		#logger.debug("I AM IN THIS IF CONDITION BIATCHES")
		flash[:notice] = "Title field should not be empty!"
		redirect_to new_user_event_path(session[:user_id])
	#end 
	else 
		@event = Event.create!(params[:event])
		flash[:notice] = "New Event Created"
		redirect_to  user_path session[:user_id]
	end
end

def show
	@event = Event.find_by_id(params[:id])
end
def update
	@event = Event.find_by_id params[:id]
    @event.update_attributes!(params[:event])
    flash[:notice] = "#{@event.title} was successfully updated."
    redirect_to user_path session[:user_id]
end

def destroy
	@event = Event.find_by_id(params[:id])
	@event.destroy
	flash[:notice] = "Event '#{@event.title}' deleted."
    redirect_to user_path session[:user_id]
end
def edit
    @event = Event.find_by_id params[:id]
end






end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def checklogin
  	if session[:user_id] == nil
	    redirect_to login_path
	    return
  	else 
  		redirect_to user_path session[:user_id]
  		return
	end
  end

  def login
  	@numUsers = User.all.size
  	flash[:notice] = "Total users = #{@numUsers}"
  end

  def create
  	auth=request.env["omniauth.auth"]
    user=User.find_by_provider_and_uid(auth["provider"],auth["uid"]) ||
      User.create_with_omniauth(auth)

    puts "CLASS OF USER IS #{user.class}"
    session[:user_id] = user.id


    #flash[:notice] = "Welcome #{user.id} AND #{user.name}"
    redirect_to user_path user.id
  end

  def failure
  end

  def destroy
  	session.delete(:user_id)
  	flash[:notice] = 'Logged out Successfully'
  	redirect_to start_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@currUser = User.find_by_id(params[:id])
		@allevents = @currUser.events
		@friends = @currUser.friends
	end

	def view
		
		@currUser = User.find_by_id(params[:id])
		# if(@currUser == nil)
		# 	flash[:notice] = "No such user"
		# 	redirect_to user_path session[:user_id]
		# end

	end

	def displayUsers
		currUser = User.find_by_id(params[:id])
		@allusers = User.notYetFriends(currUser)
	end

	def addFriend
		# friend_to_add = User.find_by_name(params[:name]);
		# currUser = User.find_by_id(params[:id])
		# Friend.create!({:uid => friend_to_add.uid, :provider=>friend_to_add.provider, 
		# 	:name=>friend_to_add.name,:first_name=>friend_to_add.first_name,
		# 	:last_name=>friend_to_add.last_name,:about=>friend_to_add.about,
		# 	:gender=>friend_to_add.gender,:work=>friend_to_add.work,
		# 	:email=>friend_to_add.email,:education=>friend_to_add.education,
		# 	:user_id => params[:id]});
		
		data_of_friend = Friend.getHash (params[:name])
		data_of_friend[:user_id] = params[:id]
		Friend.create!(data_of_friend)
		flash[:notice] = "Friend Added!! #{params[:name]}"
		redirect_to user_path params[:id]
	end

	def showFriend


	end

	def setMeeting
		currUser_events  = User.find_by_id(params[:id]).events
		otherUser_events = User.find_by_name(params[:friend_id]).events
		all_events = currUser_events + otherUser_events
		curDate = params[:curr_date]

		year = curDate[6] + curDate[7] + curDate[8]+ curDate[9]
		month = curDate[3] + curDate[4]
		day = curDate[0] + curDate[1]
		@currDate = day + "/" + month + "/" + year
		today_events = []
		free_time = [true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true]
		
		# currUser_events.each { |x|
		# 	if x.starttime.day.to_s == day && x.endtime.day.to_s == day
		# 		today_events << x
		# 	end
		# }
		# otherUser_events.each { |x| 
		# 	if x.starttime.day.to_s == day && x.endtime.day.to_s == day
		# 		today_events << x
		# 	end
		# }
		all_events.each { |event| 
			if event.starttime.day.to_s == day && event.endtime.day.to_s == day
				todays_event = event
				((todays_event.starttime.hour.to_i) .. (todays_event.endtime.hour.to_i)).each do |i| 
					free_time[i] = false
				end
			end
		}
		#VFDJVJKDFJVKJDFJV
		# logger.debug("TODAYS EVENTS: ")
		# logger.debug(today_events)
		# today_events.each do |x|
		# 	((x.starttime.hour.to_i) .. (x.endtime.hour.to_i)).each do |i| 
		# 		# logger.debug("SEE THIS BITCHES")
		# 		# logger.debug(i)
		# 		free_time[i] = false
		# 	end
		# end
		@free_slots = []
		for i in 0..23
				if free_time[i] == true
					@free_slots << i
				end
		end
		temp = ""
		# logger.debug("FREE_SLOTSSS")
		# logger.debug(@free_slots)
		# logger.debug(@free_slots.size)
		@free_slots_two = []
		for i in 0..(@free_slots.size-1)
			if i == 0
				temp = @free_slots[i].to_s + ":00 - "
			end
			# logger.debug("@free_slots[i] + 1 :")
			# logger.debug(@free_slots[i] + 1)
			# logger.debug("@free_slots[i+1]  :")
			# logger.debug(@free_slots[i+1])
				
			if @free_slots[i+1] != (@free_slots[i]+1)
				temp = temp + @free_slots[i].to_s + ":00"
				@free_slots_two << temp
				temp = @free_slots[i+1].to_s + ":00 - "
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/edit.html.haml
%center
	= form_tag user_event_path(session[:user_id], params[:id]) ,:method => :put do
		= label :event, :title, 'Title'
		= text_field :event, 'title'
		%br
		= hidden_field_tag 'event[ownerid]',session[:user_id] 

		%br

		= label :event, :starttime, 'Start Time'
		= datetime_select :event, 'starttime'
		%br

		= label :event, :endtime, 'End Time'
		= datetime_select :event, 'endtime'
		%br


		= label :event, :location , 'Location'
		= text_field :event, 'location'
		%br


		= label :event, :status , 'Status'
		= text_field :event, 'status'
		%br
		= label :event, :description , 'Description'
		= text_area :event, 'description'

		%br

		= submit_tag 'Edit Event'

app/views/events/new.html.haml
%center
	= form_tag user_events_path(session[:user_id] ,session[:user_id] ),:method =>:post do
		= label :event, :title, 'Title'
		= text_field :event, 'title'
		%br
		= hidden_field_tag 'event[ownerid]',session[:user_id] 

		= label :event, :starttime, 'Start Time'
		= datetime_select :event, 'starttime'
		%br

		= label :event, :endtime, 'End Time'
		= datetime_select :event, 'endtime'
		%br


		= label :event, :location , 'Location'
		= text_field :event, 'location'
		%br


		= label :event, :status , 'Status'
		= text_field :event, 'status'
		%br
		= label :event, :description , 'Description'
		= text_area :event, 'description'

		%br

		= submit_tag 'Create Event'

		

		

app/views/events/show.html.haml
%h2 Details about #{@event.title}

%ul#details
  %li
    Start Time:
    = @event.starttime
  %li
    End Time:
    = @event.endtime
  %li
    Status:
    = @event.status
  %li
    Location:
    = @event.location

%h3 Description:

%p#description= @event.description

%h1
  = link_to 'Delete',user_event_path,:method => :delete
  = link_to 'Edit',edit_user_event_path(session[:user_id], @event.id)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchedLums</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
%html
  %head
    %center 
      %title LUMS Scheduler!
      = stylesheet_link_tag 'application'
      = javascript_include_tag 'application'
      = csrf_meta_tags

  %body
    %center 
      %h1.title LUMS Scheduler!
      #main
        - if flash[:notice]
          #notice.message= flash[:notice]
        - elsif flash[:warning]
          #warning.message= flash[:warning]

        = yield

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchedLums</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/displayUsers.html.haml
%table#users
	%thead
		%tr
			%th User Name
	%tbody
	- @allusers.each do |user|
		%tr
			%td{:class => @title_header}= link_to user.name, addFriend_path(params[:id], user.name)
			

app/views/users/index.html.haml
%center
	%h1
		= "Welcome #{@currUser.name} (ID = #{@currUser.id})"
		%br


	%table#events
		%thead
			%tr
				%th Event Title
				%th Owner
				%th Start Time
				%th End Time
				%th Location
				%th Status
				%th Description
		%tbody
		- @allevents.each do |event|
			%tr
				%td{:class => @title_header}= link_to event.title,user_event_path(session[:user_id],event.id)
				%td=  User.find_by_id(event.ownerid).name
				%td= event.starttime
				%td= event.endtime
				%td= event.location
				%td= event.status
				%td= event.description

	= link_to 'Add New Event',new_user_event_path(session[:user_id])
	%p.Logout= link_to 'Logout',logout_path

app/views/users/setMeeting.html.haml
%table#events
	%thead
		%tr
			%th Date
			%th Free Slots
	%tbody
		%tr
			%td{:rowspan => "#{@free_slots_two.size + 1}"}= @currDate
			%td
				-@free_slots_two.each do |slot|
					%tr
						%td= slot

app/views/users/show.html.haml
%center
	%h1
		= "Welcome" 
		= link_to @currUser.name,showprofile_path 
		= " (ID = #{@currUser.id})"
		%br


	%h2
		= "My Events:"
		%br

	%table#events
		%thead
			%tr
				%th Event Title
				%th Owner
				%th Start Time
				%th End Time
				%th Location
				%th Status
				%th Description
		%tbody
		- @allevents.each do |event|
			%tr
				%td{:class => @title_header}= link_to event.title,user_event_path(params[:id],event.id)
				%td=  User.find_by_id(event.ownerid).name
				%td= event.starttime
				%td= event.endtime
				%td= event.location
				%td= event.status
				%td= event.description

	= link_to 'Add New Event',new_user_event_path(params[:id])
	%br
	%br
	%br

	%h2
		= "My Friends:"
	%center
		%table#events
			%thead
				%tr
					%th Name
			%tbody
			- @friends.each do |friend|
				%tr
					%td=  link_to friend.name,showFriend_path(params[:id],friend.name)
				
					
			
	%br
	%br
	= link_to 'Add New Friend',displayUsers_path
	%br
	%p.Logout= link_to 'Logout',logout_path

app/views/users/showFriend.html.haml
%center
	%h1
		="Find Free Slots on a Given Date"
		%br
		%br
		="Date Input Format:  day-month-year i.e 12-05-2015"


	= form_tag set_up_a_meeting_path(params[:id],params[:friend_id]), :method => :get do
		= label(:curr_date, 'Date:')
		= text_field_tag(:curr_date)
		= submit_tag('Go!')

app/views/users/view.html.haml
%h2 Details about #{@currUser.name}

%ul#details
  %li
    First Name:
    = @currUser.first_name
  %li
    Last Name:
    = @currUser.last_name
  %li
    About:
    = @currUser.about
  %li
    Gender:
    = @currUser.gender

  %li
    Work:
    = @currUser.work

  %li
    Email:
    = @currUser.email

  %li
    Education:
    = @currUser.education
    